name: Update Notebooks

on:
  schedule:
    - cron:  '0 8,20 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout binder repo
      uses: actions/checkout@v2

    - name: Pull in latest notebooks from oscovida.github.io
      run: |
        git clone \
          --depth 1 \
          --filter=blob:none \
          --no-checkout \
          git@github.com:oscovida/oscovida.github.io.git \
          .oscovida.github.io
        cd .oscovida.github.io
        git sparse-checkout set ipynb
        git checkout

        cd ..
        cp -r .oscovida.github.io/ipynb/* ipynb/
        rm -rf ipynb/oscovida

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ipynb
          git commit -m "Auto sync notebooks on $(date)"

          git push
