name: Update Notebooks

on:
  schedule:
    - cron:  '0 8,20 * * *'
  workflow_dispatch:

jobs:
  update-notebooks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout binder repo
      uses: actions/checkout@v2

    - name: Pull in latest notebooks from oscovida.github.io
      run: |
        git clone \
          --depth 1 \
          --filter=blob:none \
          --no-checkout \
          https://github.com/oscovida/oscovida.github.io.git \
          .oscovida.github.io
        cd .oscovida.github.io
        git sparse-checkout set ipynb
        git checkout

        cd ..
        cp -r .oscovida.github.io/ipynb/* ipynb/
        rm -rf ipynb/oscovida

    - name: Pull in latest notebooks from oscovida pelican content
      run: |
        git clone \
          --depth 1 \
          --filter=blob:none \
          --no-checkout \
          https://github.com/oscovida/oscovida.git \
          .oscovida
        cd .oscovida
        git sparse-checkout set tools/pelican/content/ipynb
        git checkout

        cd ..
        rm -f .oscovida/tools/pelican/content/ipynb/*.nbdata  # Not needed
        cp -r .oscovida/tools/pelican/content/ipynb/* ipynb/

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ipynb
        git commit -m "Auto sync notebooks on $(date)"

    - name: Push changes
      uses: ad-m/github-push-action@b007e7b818e33b04afd056e4c4b57ba917145d7a
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
